services:
  - type: web
    name: group-deception-study2
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DEBUG_LINKS
        value: false
      - key: DATA_DIR
        value: ./data/sessions
